### ISSUE TITLE
Wrong README for sendTransferNodeJS?

### ISSUE THREAD

**Issue by janpieper** [iota-pico/tutorials#1]
Where is the difference between these two files?

* [using-library/node-js/getNodeInfoNodeJS/README.md](https://github.com/iota-pico/tutorials/blob/4630188c2b9aeade8b090d03b38eea228031b88c/using-library/node-js/getNodeInfoNodeJS/README.md)
* [using-library/node-js/sendTransferNodeJS/README.md](https://github.com/iota-pico/tutorials/blob/4630188c2b9aeade8b090d03b38eea228031b88c/using-library/node-js/sendTransferNodeJS/README.md)

I would expect the second README to tell me something about sending a transfer, not how to get the node info.

**Comment by obany** [comment]
Too much copy and paste on my part, will get it fixed.

**Comment by obany** [comment]
Fixed and closed
